coverage:
  status:
    project:
      overall:
        target: 90%
        threshold: 0%
        if_not_found: failure
        informational: false
        only_pulls: true
    patch:
      default:
        target: 90%
        threshold: 0%
        if_not_found: failure
        informational: false
        only_pulls: true
